import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import NProgressProvider from "@/providers/nprogress";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ExternalLinkInterceptor } from "@/providers/external-link-interceptor";
import information from "@/content/information.json"

const hankedGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${hankedGrotesk.variable} flex flex-col min-h-screen antialiased`}
      >
        <NProgressProvider>
          <TooltipProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              <main className="flex-grow">{children}</main>
              <Footer info={information.footer} />
              <ExternalLinkInterceptor />
            </ThemeProvider>
          </TooltipProvider>
        </NProgressProvider>
      </body>
    </html>
  );
}
